# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default=0, upload_to='catalog-images'),
            preserve_default=False,
        ),
    ]
