# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='catalog_images'),
        ),
    ]
